### ISSUE TITLE
Possible edge scenario when using Conditional Fetching + Suspense mode

### ISSUE THREAD

**Issue by ythecombinator** [zeit/swr#372] opened 2020-05-05 17:48 UTC
The docs state that:

> In Suspense mode, data is always the fetch response (so you don't need to check if it's undefined).

It turns out that if we use suspense mode + conditional fetching, SWR is going to suspend the execution only when it gets a valid `id`, resulting in an undefined `data` object meanwhile.

As a user, I would expect that SWR throws component rendering at the moment of invocation, even — if the fetcher execution hasn't started yet — because right now I end up having to do undefined checks anyway.

Here's a working sample: https://codesandbox.io/s/conditional-fetching-suspense-b72ii

I am not quite sure if that's actually the intended behavior. If so, I'd say it definitely deserves some notice on the docs. 

Also, I tried finding some similar issues but I couldn't find any related one.

Thanks 🙏

**Comment by sergiodxa** [comment] 2020-05-05 18:10
I think this solves your use case https://github.com/zeit/swr/pull/357?

**Comment by ythecombinator** [comment] 2020-05-05 18:24
Yeah, definitely, I'd say. 

Actually, mine could be considered duplicate in face of #339. I somehow missed it when searching Github 😓

**Comment by shuding** [comment] 2020-05-12 03:45
Duplicate of #339, closing this one for now 🙏

**Closed by shuding** 2020-05-12 03:45 UTC
